package com.intern.mapping;
// Generated Oct 19, 2018 9:31:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name="function"
    ,catalog="demo"
)
public class Function  implements java.io.Serializable {


     private Integer funId;
     private String funName;
     private String funUrl;
     private Set<PageFunctions> pageFunctionses = new HashSet<PageFunctions>(0);

    public Function() {
    }

	
    public Function(String funName, String funUrl) {
        this.funName = funName;
        this.funUrl = funUrl;
    }
    public Function(String funName, String funUrl, Set<PageFunctions> pageFunctionses) {
       this.funName = funName;
       this.funUrl = funUrl;
       this.pageFunctionses = pageFunctionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fun_id", unique=true, nullable=false)
    public Integer getFunId() {
        return this.funId;
    }
    
    public void setFunId(Integer funId) {
        this.funId = funId;
    }

    
    @Column(name="fun_name", nullable=false, length=100)
    public String getFunName() {
        return this.funName;
    }
    
    public void setFunName(String funName) {
        this.funName = funName;
    }

    
    @Column(name="fun_url", nullable=false, length=100)
    public String getFunUrl() {
        return this.funUrl;
    }
    
    public void setFunUrl(String funUrl) {
        this.funUrl = funUrl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="function")
    public Set<PageFunctions> getPageFunctionses() {
        return this.pageFunctionses;
    }
    
    public void setPageFunctionses(Set<PageFunctions> pageFunctionses) {
        this.pageFunctionses = pageFunctionses;
    }




}


