package com.intern.mapping;
// Generated Oct 19, 2018 9:31:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="demo"
)
public class Role  implements java.io.Serializable {


     private int roleId;
     private String roleName;
     private Set<PageFunctions> pageFunctionses = new HashSet<PageFunctions>(0);
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

	
    public Role(int roleId) {
        this.roleId = roleId;
    }
    public Role(int roleId, String roleName, Set<PageFunctions> pageFunctionses, Set<User> users) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.pageFunctionses = pageFunctionses;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="role_id", unique=true, nullable=false)
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="role_name", length=100)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="role")
    public Set<PageFunctions> getPageFunctionses() {
        return this.pageFunctionses;
    }
    
    public void setPageFunctionses(Set<PageFunctions> pageFunctionses) {
        this.pageFunctionses = pageFunctionses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="role")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


